prgrms-web-devcourse-final-project/WEB2_3_BlockB_FE

package.json, pnpm-lock.yaml, postcss.config.js, src/css/tailwind.css, tailwind.config.js, vite.config.ts
- close #5 
테일윈드 4.0.6에서  3.4.1로 다운그레이드
처음에는 4.0.6으로 설치 했었는데 커스텀 컬러가 적용 안 되는 이슈가 있었는데
4로 새로 수정된 버전을 공부해서 다시 적용하려다 시간을 너무 낭비해서 기존에 알던 3버전으로 다운그레이드 하였습니다.
어떤 변경 사항이 있나요?
=> 테일윈드 4.0 .6에서  3.4.1로 다운그레이드

.gitignore, netlify.toml
- close #12 
- toml 파일 생성했습니다. env gitignore에 추가했습니다.
어떤 변경 사항이 있나요?
=> bug: 배포 오류 수정

package.json, src/assets/icons/progress/progress-icon.ts, src/assets/icons/progress/turn-progress.svg, src/assets/icons/progress/turn-progress_checked.svg, src/components/debate-zone/generating-room/CheckBoxGroups.tsx, src/components/debate-zone/generating-room/GeneratingRoom.tsx, src/components/debate-zone/generating-room/ProgressIndicator.tsx, src/components/debate-zone/generating-room/RoomInputCard.tsx, src/components/debate-zone/ongoing-debate/ReportModal.tsx, src/constants/index.ts, src/stores/roomStateStore.ts, src/types/debateRoomType.d.ts
#14 #4 
- close #4 #14 
기획 변경으로 인해 generating Room에 선택지 추가함 
발언횟수 선택지 추가및 dbkey 추가]
어떤 변경 사항이 있나요?
=> feat:발언횟수 선택지 추가및 dbkey 추가

.github/workflows/deploy-netlify.yml
- close #16 
-  배포 오류로 인한 yml 파일 수정했습니다.
어떤 변경 사항이 있나요?
=> bug: yml 파일 수정

src/components/debate-zone/waiting-room/WaitingInfoDrodown.tsx, src/components/debate-zone/waiting-room/WaitingRoom.tsx, src/constants/index.ts, src/pages/DebateZone.tsx, src/stores/roomStateStore.ts, src/types/debateRoomType.d.ts
<!--- #4 #14 
- close #4 #14 
roomStore로 토론방 개설 정보 waitingroom dropdown으로 공유
null아님보장연산추가(타입 애러 해결)
어떤 변경 사항이 있나요?
=> Feat: roomStore로 토론방 개설 정보 waitingroom dropdown으로

src/css/fonts.css, tailwind.config.js
- close #31 
폰트 추가
어떤 변경 사항이 있나요?
=> feat: font 추가

src/components/common/Header.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationList.tsx
- close #38 
- 헤더에 알림 추가
- 헤더 밑줄 추가
어떤 변경 사항이 있나요?
=> Feat: 헤더에 알림 추가

src/components/debate-zone/ongoing-debate/OngoingDebate.tsx, src/components/main/DebateSimpleInfo.tsx, src/components/my-page/DebateTab.tsx, src/components/my-page/FollowTab.tsx, src/components/my-page/NewsTab.tsx, src/pages/Login.tsx, src/pages/Main.tsx
- close #53 
메인 페이지, 마이 페이지, 로그인 페이지 수정
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가
=> Feat: 메인 페이지, 마이 페이지, 로그인 페이지 수정

src/components/debate-zone/ReplayDebate.tsx, src/components/debate-zone/VoteButton.tsx, src/components/debate-zone/VoteResult.tsx, src/components/debate-zone/VoteRoom.tsx, src/components/debate-zone/observer-mode/ObserverMatchingInterface.tsx, src/components/debate-zone/observer-mode/ObserverOngoingRoom.tsx, src/components/debate-zone/observer-mode/ObserverWaitingRoom.tsx, src/components/debate-zone/ongoing-debate/ChatWindow.tsx, src/components/debate-zone/ongoing-debate/MessageItem.tsx, src/components/debate-zone/ongoing-debate/MessageSection.tsx, src/components/debate-zone/ongoing-debate/OngoingDebate.tsx, src/components/debate-zone/waiting-room/WaitingInfoDrodown.tsx, src/components/debate-zone/waiting-room/WaitingRoom.tsx, src/pages/DebateZone.tsx, src/pages/ObservingZone.tsx, src/types/debateRoomType.d.ts
<!--- ex) #54 
-
chatbubble 색상 변경
투표 버튼 디자인 수정
isObserver optional 처리
VoteInfo export 제거 (type.d.ts)
큰 화면에서 css 처리
어떤 변경 사항이 있나요?
=> Design. type애러 및 isObserver optional처리 + 큰 화면 시 css 깨짐 오류 처리 + chat bubble 색 변경

src/components/debate-room/DebateRoomList.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationList.tsx, src/pages/DebateRooms.tsx, src/pages/Debaters.tsx, src/pages/News.tsx
- close #55 
- Fix: 알림,토론방, 토론 유저 퍼블리싱 수정
어떤 변경 사항이 있나요?
=> Fix: 알림,토론방, 토론 유저 퍼블리싱 수정

src/components/common/TopButton.tsx, src/layouts/RootLayout.tsx
<!--- ex) #61 
- close #61 
탑 버튼 구현 및 pathname 별로 색상 변경 로직 추가
어떤 변경 사항이 있나요?
=> Feat. 탑버튼 구현

src/components/debate-room/DebateRoomList.tsx
<!--- ex) #65 
- close #65
어떤 변경 사항이 있나요?
=> Feat. 토론 리스트 스켈레톤 ui

src/components/common/skeleton/debate/DebateListSkeleton.tsx, src/components/common/skeleton/debate/TopDebateListSkeleton.tsx, src/components/common/skeleton/news/CatecorySkeleton.tsx, src/components/common/skeleton/news/FilterSearchSkeleton.tsx, src/components/common/skeleton/news/NewsDetailSkeleton.tsx, src/components/debaters/DebateList.tsx, src/components/debaters/TopDebateList.tsx
- close #69 
- 유저 검색/순위 스켈레톤
어떤 변경 사항이 있나요?
=> Feat: 유저 검색/순위 스켈레톤

src/components/common/skeleton/mypage/CommonSimpleInfoSkeleton.tsx, src/components/common/skeleton/mypage/MyPageSkeleton.tsx, src/components/common/skeleton/mypage/ProfileSimpleInfoSkeleton.tsx, src/components/common/skeleton/mypage/ProfileUpdateSkeleton.tsx, src/components/my-page/CommonSimpleInfo.tsx, src/components/my-page/ProfileSimpleInfo.tsx, src/components/my-page/ProfileUpdate.tsx, src/pages/MyPage.tsx
- close #71 
- 마이페이지 스켈레톤
어떤 변경 사항이 있나요?
=> Feat: mypage skeleton

src/components/common/skeleton/debate/DebateRoomSkeleton.tsx, src/components/common/skeleton/main/DebateSimpleInfosSkeleton.tsx, src/components/common/skeleton/main/NewsSimpleInfosSkeleton.tsx, src/components/debate-room/DebateRoomList.tsx, src/components/main/DebateSimpleInfos.tsx, src/components/main/NewsSimpleInfos.tsx
<!--- ex) #75
- close #75
main page + debate-rooms-list skeleton
어떤 변경 사항이 있나요?
=> feat: main page + debate-rooms-list skeleton

src/components/common/Header.tsx
- close #78
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가
=> feat: 반응형 헤더 구현

src/components/common/skeleton/news/CatecorySkeleton.tsx, src/components/news/category.tsx, src/pages/News.tsx, src/pages/NewsDetail.tsx
- close #77 
- 뉴스페이지 반응형 구현
어떤 변경 사항이 있나요?
=> Feat: 뉴스페이지 반응형 구현

src/components/main/NewsSimpleInfo.tsx, src/components/main/NewsSimpleInfos.tsx, src/pages/Main.tsx
- close #81 
메인 페이지 반응형 구현
어떤 변경 사항이 있나요?
=> feat: 메인 페이지 반응형 구현

src/components/common/Pagenation.tsx, src/components/my-page/CommonSimpleInfo.tsx, src/components/my-page/DebateTab.tsx, src/components/my-page/FollowTab.tsx, src/components/my-page/NewsTab.tsx, src/components/my-page/ProfileSimpleInfo.tsx, src/components/my-page/ProfileUpdate.tsx, src/pages/MyPage.tsx
- close #87 
마이페이지 반응형 구현
페이지네이션 숫자 최대 5개까지
ex) 전체 페이지가 9개이고 현재 페이지가 4일 때  2 3 4 5 6 이런식으로 나옴
어떤 변경 사항이 있나요?
=> Feat: 마이페이지 반응형 구현 (+페이지네이션 수정)

src/components/debate-zone/InfoDrodown.tsx, src/components/debate-zone/observer-mode/AudienceList.tsx, src/components/debate-zone/observer-mode/AudienceListBox.tsx, src/components/debate-zone/observer-mode/ChatObserverChatBubble.tsx.tsx, src/components/debate-zone/observer-mode/ObserverChatSection.tsx, src/components/debate-zone/observer-mode/ObserverChatWindow.tsx, src/components/debate-zone/observer-mode/ObserverMatchingInterface.tsx, src/components/debate-zone/observer-mode/ObserverMobileChatMenu.tsx, src/components/debate-zone/observer-mode/ObserverMobileTab.tsx, src/components/debate-zone/observer-mode/ObserverOngoingRoom.tsx, src/components/debate-zone/observer-mode/ObserverWaitingRoom.tsx, src/components/debate-zone/waiting-room/WaitingRoom.tsx
= #90
- close #90 
참관자 대기방 반응형
참관자 대기완료 반응형
토론방 정보 드롭다운 => info 버튼 변경
참관자 토론중 탭 반응형 구현
참관자 상단 모바일 메뉴바 구현
참관탭 토론탭
어떤 변경 사항이 있나요?
토론 채팅창 사이즈 조정에 어려움이 있는데 모바일 화면의 h 조정을 내일 함께 리뷰해 주셨으면 좋겠습니다.
=> Feat. observing zone responsive publishing

src/components/common/skeleton/debate/DebateRoomSkeleton.tsx, src/components/debate-room/DebateRoomList.tsx, src/components/debate-room/FilterSection.tsx, src/components/debate-room/SortSection.tsx, src/pages/DebateRooms.tsx
- close #84 
- 토론방 리스트 스켈레톤 수정
-  DebateRoom.tsx 에서 필터, 정렬 세션 컴포넌트 분리
- 필터 세션에서 map을 사용해 코드 간결화 + props로 넘겨줌
- DebateRoomList.tsx pc버전 모바일 버전 분리 
어떤 변경 사항이 있나요?
- 구조를 컴포넌트 분리해서 바꾸고 반응형을 추가했습니다.
=> Feat: 전체 토론방 반응형

src/components/common/Header.tsx
=> feat: 랜딩페이지 헤더 반응형 구현

src/components/admin/FilterButton.tsx, src/components/admin/Modal.tsx, src/components/admin/ReportTable.tsx, src/components/common/Pagenation.tsx, src/pages/Admin.tsx
- close #94 
- admin 페이지 반응형 
- 되도록  틀을 안 바꾸려고 했습니다.
- 전체적으로 w-full 을 주었으며 md, sm 사이즈 별로 폰트 크기를 조정했습니다.
어떤 변경 사항이 있나요?
=> Feat: admin 페이지 반응형

src/components/debate-zone/observer-mode/ChatObserverChatBubble.tsx.tsx, src/components/debate-zone/observer-mode/DebateChatObserverMode.tsx, src/components/debate-zone/observer-mode/ObserverChatSection.tsx, src/components/debate-zone/observer-mode/ObserverChatWindow.tsx, src/components/debate-zone/observer-mode/ObserverOngoingRoom.tsx, src/components/debate-zone/observer-mode/OngoingInfo.tsx
#100 
- close #100 
어떤 변경 사항이 있나요?
사이즈 별로 chatwindow가 한눈에 안 보일 수도 있을 것 같은데 한번 확인해주십시오
=> Bug: debate observing publishing css bug fix

src/components/main/DebateSimpleInfo.tsx, src/pages/Main.tsx
- close #107 
메인 debate top10 탭 페이지 반응형 구현
태블릿 버전: 크기 줄임
모바일 버전: 카테고리 이미지 제거 및 폰트 사이즈 조정, 타이틀 줄 2줄 
어떤 변경 사항이 있나요?
태블릿 버전
모바일 버전
=> feat: 메인 debate top10 탭 페이지 반응형 구현

src/components/common/skeleton/main/NewsSimpleInfosSkeleton.tsx, src/components/main/NewsSimpleInfo.tsx, src/components/main/NewsSimpleInfos.tsx
- close #109 
메인페이지 반응형 스켈레톤 구현
어떤 변경 사항이 있나요?
=> Feat: 메인페이지 반응형 스켈레톤 구현

src/components/common/Header.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationList.tsx
- close #105 
- 헤더 고정으로 바꿨습니다
- 알림 css는 status 상태에 따라 어두운 버전, 흰 바탕 버전으로 나뉘게 바꾸었습니다.
- 알림 반응형 완료했습니다.
어떤 변경 사항이 있나요?
=> Feat: 알림 반응형 및 Header 고정

src/components/common/TopButton.tsx
- close #113 
- 탑버튼 배경색 추가했습니다.
- 블랙과 화이트로 지정했습니다.
어떤 변경 사항이 있나요?
=> Feat: 탑버튼 bg 추가

src/components/debate-zone/InfoDrodown.tsx, src/components/debate-zone/ParticipantBox.tsx, src/components/debate-zone/ProfileCard.tsx, src/components/debate-zone/ReplayDebate.tsx, src/components/debate-zone/VoteRoom.tsx, src/components/debate-zone/observer-mode/AudienceList.tsx, src/components/debate-zone/observer-mode/DebateChatObserverMode.tsx, src/components/debate-zone/observer-mode/ObserverChatWindow.tsx, src/components/debate-zone/observer-mode/ObserverMatchingInterface.tsx, src/components/debate-zone/observer-mode/ObserverMobileChatMenu.tsx, src/components/debate-zone/observer-mode/ObserverMobileTab.tsx, src/components/debate-zone/observer-mode/ObserverOngoingRoom.tsx, src/components/debate-zone/observer-mode/ObserverWaitingRoom.tsx, src/components/debate-zone/observer-mode/OngoingInfo.tsx, src/components/debate-zone/ongoing-debate/ChatWindow.tsx, src/components/debate-zone/ongoing-debate/MessageItem.tsx, src/components/debate-zone/ongoing-debate/MessageSection.tsx, src/components/debate-zone/ongoing-debate/MobileChatMenu.tsx, src/components/debate-zone/ongoing-debate/OngoingDebate.tsx, src/components/debate-zone/ongoing-debate/ReportModal.tsx, src/components/debate-zone/ongoing-debate/TurnProgress.tsx, src/pages/DebateZone.tsx, src/pages/ObservingZone.tsx, src/stores/observingStateStore.ts, src/stores/reportModalStore.ts, tailwind.config.js
#102 
- close #102
- **회원가입 로딩 애니메이션 속도 조정** (`fix: singup loading animation slow 조정`)  
- **InfoDropdown 모바일 UI 오류 수정** (채팅창과 글씨가 겹치는 문제 해결)  
- **VoteRoom 안내 메시지 반응형 개선** (일정 너비 이하에서 두 줄 처리, 투표 버튼 수정)  
- **VoteRoom 추가 수정** (`fix:voteroom fix`)  
- **ReportModal이 `portal`을 사용하도록 변경** (body에 렌더링되도록 개선)  
- **Observer AudienceList에서 신고 모달 열기 기능 추가** (`feat: observer audiencelist 신고 모달 열기 기능 추가`)  
- **ReportModal을 store화하여 이벤트 버블링으로 인한 오류 해결**  
- **ChatBubble 최대 너비 초과 시 `break-words` 처리 추가**  
- **모바일 창 높이를 `calc` 연산으로 수동 조정** (`fix: mobile 창 높이 calc 연산으로 수동 처리`)  
- **Ongoing Debate 채팅창 최소 320px까지 반응형 지원**  
이렇게 정리하면 변경사항이 명확하게 전달될 거야! 🚀
어떤 변경 사항이 있나요?
다른 컴퓨터 화면에서 깨짐이 없는지 확인
=> Bug debate responsive css error fix

src/components/debate-zone/InfoDrodown.tsx, src/components/debate-zone/waiting-room/Ment.tsx, src/components/debate-zone/waiting-room/WaitingRoom.tsx, src/hooks/usInterval.ts
- close #118 
WaitingRooms.tsx 무한 랜더링 리팩토링
크롬 확장 프로그램인 reat developer tools에서 반짝 거리는 나머지는 css 변겨으로 인한 것임
어떤 변경 사항이 있나요?
=> feat:WaitingRooms.tsx 무한 랜더링 리팩토링

src/components/common/Header.tsx, src/components/common/TopButton.tsx, src/components/my-page/ProfileUpdate.tsx, src/components/news/NewsList.tsx, src/pages/Main.tsx, src/pages/MyPage.tsx
#123 
- close #123 
- 마이페이지 프로필 편집 및 테블릿 px 수정
- 해더 공간 뜨는 이슈 수정
- 탑 버튼 모바일 위치 조정
- newlist에서 탑버튼 안 보이는 문제 해결 (useRef 사용해서 변경)
어떤 변경 사항이 있나요?
=> Bug responsive css details fix

pnpm-lock.yaml, src/api/axios.ts, src/api/news.ts
=> feat:axios 설치 및 기본 설정

src/api/admin.ts, src/api/axios.ts, src/components/admin/AdminFilteringButtons.tsx, src/components/admin/AdminTab.tsx, src/components/admin/FilterButton.tsx, src/components/admin/Modal.tsx, src/components/admin/ReportTable.tsx, src/components/common/LoadingSpinner.tsx, src/constants/index.ts, src/hooks/useDebounce.ts, src/hooks/usePagenation.ts, src/pages/Admin.tsx, src/types/reportType.d.ts
#130 
- close #130 
- 퍼블리싱 시 임시로 만들어둔 가독성, 식별성 있게 변수명 수정
- 신고 목록 조회
- 신고 상세 조회
- 신고 처리
- 신고 복구
- 신고 처리 수정
- 페이지네이션 처리
- 어드민 페이지 컴포넌트화
- 로딩 스피너 구현 및 공통 컴포넌트화
- role에 따라 header 메뉴의 admin 탭 가시 여부 구현(미완 - 타 팀원 Header.tsx 수정 중 병합 후 추가 예정)
- 페이지네이션 오류 수정
어떤 변경 사항이 있나요?
hments/assets/77264c6f-e22d-4313-b189-ca85bf251057)
-백엔드에서 완성되지 않은 api를 추가 요청한 것을 아직 못 받아서 추후에 추가해야 하는 사안이 몇가지 있습니다.
TODO: 
- assignedUserId 값 로드 확인 (백엔드 추가 사안 배포 전)
- reportedAt 값 로드 확인  (백엔드 추가 사안 배포 전)
- user.ts로 현재 로그인한 admin userId 동적으로 신고 처리 호출에 입력
- admin.ts 수동으로 추가하고 있었던 accesstoken 값, 로그인 구현 완료되면 동적으로 interceptor로 추가
=> Feat admin page

src/App.tsx, src/layouts/PrivateRoute.tsx, src/layouts/PublicRoute.tsx, src/layouts/RootLayout.tsx, src/pages/Login.tsx, src/pages/OAuthCallback.tsx, src/pages/Signup.tsx, src/stores/authStore.ts
- close #131 
- 비 로그인시 랜딩, 로그인 페이지로 이동
- 로그인시 랜딩, 로그인페이지로 이동 불가
- 로그인 페이지 반응형 추가
- 회원가입 페이지 css 수정
- 회원가입 페이지 반응형 추가
어떤 변경 사항이 있나요?
- pr 한번 하고 풀 받고 리프레쉬 토큰 적용 하겠습니다..
=> Feat: 로그인 연동 초안 

src/api/user.ts, src/components/common/Header.tsx, src/pages/OAuthCallback.tsx, src/stores/userStore.ts
- close #140 
- 유저 스토어에서 유저 정보 불러오기
어떤 변경 사항이 있나요?
=> Feat: 유저 스토어 수정

src/App.tsx, src/pages/Login.tsx, src/pages/OAuthCallback.tsx
- close #149 
- 로그인 로직 수정 
- 인가코드 보내는 로직으로 수정 
- app 라우팅 수정
- callback 수정 중 
어떤 변경 사항이 있나요?
- 구글 말고는 저한테 작동 안하긴 해서 좀 더 살펴봐야 할 것 같습니다.
- 임시로 먼저 PR 올릴게요
- data 값에 id 가 없어서 마이페이지 이동이 불가능 한 것 같습니다. 수기로 이동해야합니다.
=> Fix: 로그인 로직 수정

src/components/news/NewsList.tsx
- close #152 
뉴스페이지 더보기 버튼 수정
어떤 변경 사항이 있나요?
=> style: 뉴스페이지 더보기 버튼 수정

package.json, src/components/admin/AdminFilteringButtons.tsx, src/components/admin/AdminModal.tsx, src/components/common/Header.tsx, src/components/common/Modal.tsx, src/components/debate-zone/RoomActionButtons.tsx, src/components/debate-zone/ongoing-debate/OngoingDebate.tsx, src/components/debate-zone/waiting-room/WaitingRoom.tsx, src/components/news/NewsList.tsx, src/contexts/DebateWebSocketContext.tsx, src/hooks/useNewsInfoParams.ts, src/pages/DebateZone.tsx, src/pages/GeneratingRoom.tsx, src/pages/NewsDetail.tsx, src/pages/OAuthCallback.tsx, src/pages/Signup.tsx
#163
- close #163
1. 모달 구현
2. 웹소켓 연결 stomp js 로 변경
3. DebateWebsocketContext 생성
4. react-use-websocket 라이브러리 삭제
5. useWebsocket 코드 주석 처리 (후에 참고 => stomp + context 코드 변환)
- `useWebsocket` 코드에 주석을 추가하여 후속 작업을 위해 참고할 수 있도록 처리함 (stomp + context 코드로 변환 예정).
어떤 변경 사항이 있나요?
context api 사용 코드 웹소켓 하시는 분은 참고해주세요
=> Feat debate participants websocket

src/App.tsx, src/components/common/Modal.tsx, src/components/common/skeleton/news/NewsSkeleton.tsx, src/components/user-page/CommonSimpleInfo.tsx, src/components/user-page/FollowTab.tsx, src/components/user-page/ProfileUpdate.tsx, src/hooks/useTokenRefresh.ts, src/layouts/AdminRoute.tsx, src/pages/Debaters.tsx, src/pages/Login.tsx, src/pages/OAuthCallback.tsx, src/pages/Signup.tsx, src/types/debateRoomResponseType.d.ts
=> Bug 수정 사항 오류 처리

src/App.tsx, src/components/common/Header.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationList.tsx, src/hooks/useGetNotifications.ts, src/layouts/RootLayout.tsx, src/pages/UserPage.tsx, src/types/type.d.ts
- close #183 
알림 삭제 모달이 알림 모달을 벗어나는 css 수정
로그아웃일 때 헤더에서 api 요청으로 생기는 오류 수정
어떤 변경 사항이 있나요?
=> Refactor: 알림 관련 여러 사항

src/components/notification/NotificationItem.tsx
- close #186 
토론방 일림 입장하기 제거
어떤 변경 사항이 있나요?
=> bug:토론방 일림 입장하기 제거

src/components/main/NewsSimpleInfo.tsx, src/components/main/NewsSimpleInfos.tsx, src/components/news/NewsList.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationList.tsx, src/components/user-page/FollowTab.tsx, src/pages/News.tsx, src/types/type.d.ts
- close #188 
페이지 전역 스타일 최적화
사용하지 않는 코드 제거
알림 전체 삭제시 모달로 삭제 여부 확인
어떤 변경 사항이 있나요?
=> Style:페이지 전역 스타일 최적화 & refacotr: 사용하지 않는 코드 제거 & feat: 알림 전체 삭제시 모달로 삭제 여부 확인

src/components/common/Header.tsx, src/components/common/TopButton.tsx, src/components/landing/LandingServieDescription.tsx, src/components/news/NewsList.tsx, src/pages/GeneratingRoom.tsx, src/pages/News.tsx
- close #195 
랜딩페이지 - 마우스 이미지가 gsap 효과 안 생기도록 수정
뉴스 페이지 - 스케일시 화면 짤림 수정, 중복 코드 제거
헤더 - 어드민 계정 알림 미표시, md 사이즈에서 텍스트 조정
토론 생성 페이지 - 탑 버튼 수정
어떤 변경 사항이 있나요?
=> Style: 스타일 최적화

src/api/axios.ts
- close #197 
axios get 요청시 URL을 통한 SSRF 및 자격 증명 유출 방지를 위한 isSafeURL 함수 추가
어떤 변경 사항이 있나요?
=> refactor:axios get 요청시 URL을 통한 SSRF 및 자격 증명 유출 방지를 위한 isSafeURL 함수 추가

src/components/archived-room/ArchivedRoomDebateChat.tsx, src/components/archived-room/ArchivedRoomObserverChat.tsx, src/components/debate-zone/observer-mode/ObserverOngoingRoom.tsx, src/components/debate-zone/ongoing-debate/OngoingDebate.tsx, src/contexts/DebateWebSocketContext.tsx
#207 
- close #207 
웹소켓에 투표 타이머 기능 추가
(+아카이빙, 토로방 css 수정)]
어떤 변경 사항이 있나요?
현재 배포 상황 때문에 실제 timer 가 렌더링 되는 부분의 코드는 업데이트 안 했습니다. context api와 훅과 함수만 구현된 상황입니다.
=> feat: 웹소켓에 투표 타이머 기능 추가 (+아카이빙 css 수정)

index.html, src/pages/DebateRooms.tsx
- close #213 
- 에러 코드 주석처리
- 파비콘 넣기
어떤 변경 사항이 있나요?
=> Bug. debateroom error blocking

src/api/debatezone.ts, src/components/debate-zone/ReplayDebate.tsx, src/components/debate-zone/observer-mode/DebaterList.tsx, src/components/debate-zone/observer-mode/ObserverChatWindow.tsx, src/components/debate-zone/observer-mode/ObserverMobileChatMenu.tsx, src/components/debate-zone/observer-mode/ObserverOngoingRoom.tsx, src/components/debate-zone/observer-mode/ObserverVoteRoom.tsx, src/components/debate-zone/observer-mode/ObserverWaitingRoom.tsx, src/components/debate-zone/observer-mode/ObserverWinByDefault.tsx, src/components/debate-zone/observer-mode/OngoingInfo.tsx, src/components/debate-zone/ongoing-debate/Counter.tsx, src/components/debate-zone/ongoing-debate/MessageSection.tsx, src/contexts/DebateWebSocketContext.tsx, src/contexts/ObserverWebSocketContext.tsx, src/pages/DebateRooms.tsx, src/pages/GeneratingRoom.tsx, src/pages/ObservingZone.tsx, src/types/debateRoomType.d.ts
#210 
- close #210 
웹소켓 부전승 기능 구현 완료
어떤 변경 사항이 있나요?
=> feat: 웹소켓 부전승 구현 완료

src/pages/DebateRooms.tsx
- close #224 
- 바뀌어있던 디베이트룸 코드추가
어떤 변경 사항이 있나요?
=> Fix: 바뀌어있던 디베이트룸 코드추가

src/components/debate-zone/ReplayDebate.tsx, src/components/debate-zone/observer-mode/ObserverMatchingInterface.tsx, src/components/debate-zone/observer-mode/ObserverWaitingRoom.tsx, src/components/debate-zone/waiting-room/WaitingRoom.tsx
#228 
- close #228 
웹소켓 플로우 버그 수정했습니다
어떤 변경 사항이 있나요?
개발 환경에서 QA 
=> fix: 웹소켓 플로우 버그 수정

src/components/notification/NotificationList.tsx
- close #231 
무한 스크롤 안 되는 현상 해결
어떤 변경 사항이 있나요?
=> bug: 무한 스크롤 안 되는 현상 해결

src/components/common/Footer.tsx
- close #235 
footer의 blog와 linkedin 클릭시 링크트리로 이동
어떤 변경 사항이 있나요?
=> feat:footer의 blog와 linkedin 클릭시 링크트리로 이동
